Enhancing SSH Connection Compatibility with Cursor
coder/vscode-coder pull request #225
Opened 2024-03-06 16:21 UTC by RyousukeUchino

Previous MR https://github.com/coder/vscode-coder/pull/221

## Overview

I have been a dedicated user of both Coder and Cursor. However, I've encountered persistent issues when attempting to connect to the Coder workspace via Cursor ([Cursor](https://cursor.sh/)). These issues range from receiving 404 errors to SSH connection failures, preventing any access to the workspace. The root cause of these problems lies in the necessity to use Cursor's built-in Open Remote - SSH extension, `anysphere.open-remote-ssh`, for successful SSH connections.

### Changes Made

I've confirmed that users utilizing Cursor can simply specify `anysphere.open-remote-ssh` explicitly within the Coder plugin without any issues coexisting with `ms-vscode-remote.remote-ssh`. Therefore, I've made a straightforward update to check for the existence of `anysphere.open-remote-ssh` and use it preferentially if available. This eliminates the need to remove any dependencies.

With this MR, I'm hopeful for a seamless integration between Cursor and Coder, which I personally believe is the best combination.

2024-03-06 17:42 UTC, kylecarbs requested changes
Awesome description, thanks for the contribution!

I'd rather we only get the other extension if the official remote extension isn't found.

2024-03-06 23:58 UTC, kylecarbs approved these changes

2024-03-06 23:58 UTC, kylecarbs commented on src/extension.ts
> +  // If it is not found, then the extension "ms-vscode-remote.remote-ssh" is sought as a fallback.
Nit: Let's add a comment to explicitly mention this is for non-official VS Code distributions. Just so in the future we know!

2024-03-12 20:29 UTC, merged

2024-03-13 18:39 UTC, code-asher commented
Released in 0.1.35!

2024-03-25 20:26 UTC, stobias123 commented
is there configuration required to make this work? I'm still getting 404 errors when trying to open a workspace with cursor.

2024-03-25 20:28 UTC, kylecarbs commented
Seems like something might be wrong with Cursor's Remote SSH here.

I'd be surprised if it's supposed to download Microsoft's official server.

2024-03-27 19:57 UTC, code-asher commented
Do you have the open remote SSH extension installed?  Maybe it is using the official one?  You should only have the open remote one installed.