feat: Align remote ssh naming with coder cli
coder/vscode-coder pull request #75
Opened 2023-04-05 04:50 UTC by Liorba

coder's cli tool allow users to configure ssh conection to their remote hosts.
as part of it's configuration, he generate ssh config  host to the dedicated user's machine.
The patten used by the cli tool, is not align with the one user by the vscode extension. 
This mismatch between  coder cli and the vscode extension, cause errors when trying to connect to remote host.

Key differences:
1. the host pattern [generated](https://github.com/coder/coder/blob/929589ddfa90ee55928fe0830d225f030cba7344/cli/configssh.go#L352) by the coder cli is `coder.<workspace-name>.<agent>`. currently the default agent is main
   the vscode extension is expecting the pattern `coder-vscode--<workspace-owner>--<workspace-name>--<agent?>`
2. owner / user is not encoded in the ssh host name genereated by coder cli
3. the cli [allows](https://github.com/coder/coder/blob/929589ddfa90ee55928fe0830d225f030cba7344/cli/configssh.go#L507) the user to set different prefix other then `coder`

This PR is set to close the gap between the 2 and make sure hosts created by the cli can be connected from the vscode extension

2023-04-05 16:38 UTC, kylecarbs requested changes
Hey @Liorba, I'm a bit confused by this contribution. We don't want `coder config-ssh` to interact with the VS Code extension at all, because they are truly separate experiences.

Could you explain more of the problem this solves?

2023-04-05 16:38 UTC, kylecarbs commented on src/commands.ts
> +    const remoteAuthority = `ssh-remote+${Remote.Prefix}.${workspaceName}.main` //main is the default agent
`main` is not the default name for an agent. It can be anything that a user defines!

2023-04-05 16:38 UTC, kylecarbs commented on src/remote.ts
> +    // }
This needs to be checked, otherwise Coder will activate on any remote SSH connection, which will cause errors to appear on non-Coder connections.

2023-04-05 21:33 UTC, Liorba commented
The reason for that is the ability to use the vscode extension to connect to workspaces that was configured using the config ssh option.
For example. I have a workspace that I'm connected to using ssh that I already configured via the cli.
I want to seamlessly be able to connect to it and work.with it using the extension.

2024-10-31 21:08 UTC, code-asher commented
Closing as stale, but happy to take another look if this becomes active again.

2024-10-31 21:08 UTC, closed without merging